name: Deploy to Github Pages


on:
  workflow_dispatch:
  push:
    branches: "main"

#permissions et autorisations
permissions:
  contents: read
  pages: write
  id-token: write

# Autorisation des deploiements
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    # se placer dans app
    defaults:
      run:
        shell: bash
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Installer les dépendances
      - name: Install dependencies
        run: npm ci
      # Faire le build
      - name: Build
        run: npm run build
      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.0.0
        with:
          name: artifact
          path: ./app/dist
  # faire la mise en ligne sur GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configurer github Pages
        uses: actions/configure-pages@v3.0.6
        id: pages
      - name: Deployer Github pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
        with:
          artifact_name: artifact
